// Assets/CoreEngine/Tests/PaletteSyncTests.cs
//
// Guards the ONE duplication this presentation pass introduced: the authored
// material palette exists in C# (MaterialPalette, the authoritative table) and
// is mirrored in HLSL (Raymarch.compute's MaterialAlbedo), because wiring a new
// registry buffer through RaymarchFeature's render-graph pass would have meant
// touching render setup for a colour change.
//
// A silent mismatch between the CPU palette (debug overlays, tools) and the GPU
// palette (what you actually look at) is exactly the kind of drift nobody
// notices for a month, so it is a test rather than a comment asking nicely.
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text.RegularExpressions;
using NUnit.Framework;

public class PaletteSyncTests
{
    private const string ShaderPath = "Assets/CoreEngine/Rendering/Raymarch.compute";

    private static Dictionary<byte, float[]> ParseShaderPalette()
    {
        string src = File.ReadAllText(ShaderPath);
        int start = src.IndexOf("float3 MaterialAlbedo(uint mat)");
        Assert.Greater(start, 0, "MaterialAlbedo not found in " + ShaderPath);
        int end = src.IndexOf('}', start);
        string body = src.Substring(start, end - start);

        var rx = new Regex(@"mat\s*==\s*(\d+)u\)\s*return\s*float3\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)\s*\)");
        var map = new Dictionary<byte, float[]>();
        foreach (Match m in rx.Matches(body))
        {
            byte id = byte.Parse(m.Groups[1].Value);
            map[id] = new[]
            {
                float.Parse(m.Groups[2].Value, CultureInfo.InvariantCulture),
                float.Parse(m.Groups[3].Value, CultureInfo.InvariantCulture),
                float.Parse(m.Groups[4].Value, CultureInfo.InvariantCulture),
            };
        }
        return map;
    }

    [Test]
    public void ShaderPalette_MatchesMaterialPalette()
    {
        var shader = ParseShaderPalette();
        byte[] authored =
        {
            Materials.Stone, Materials.Grass, Materials.Sand, Materials.MossyStone,
            Materials.Water, Materials.Snow, Materials.Sandstone, Materials.JungleGrass,
            Materials.Deepstone, Materials.Lava, Materials.Honey, Materials.Obsidian,
        };

        foreach (byte id in authored)
        {
            Assert.IsTrue(shader.ContainsKey(id),
                $"material {id} is authored in MaterialPalette but missing from the shader's MaterialAlbedo");
            var cpu = MaterialPalette.Of(id);
            float[] gpu = shader[id];
            Assert.AreEqual(cpu.R, gpu[0], 0.0005f, $"material {id} red channel differs (CPU vs shader)");
            Assert.AreEqual(cpu.G, gpu[1], 0.0005f, $"material {id} green channel differs (CPU vs shader)");
            Assert.AreEqual(cpu.B, gpu[2], 0.0005f, $"material {id} blue channel differs (CPU vs shader)");
        }
    }

    [Test]
    public void EveryGeneratedMaterial_HasAnAuthoredColour()
    {
        // A material generation can actually place must never fall through to
        // the "unauthored" magenta.
        byte[] generated =
        {
            Materials.Stone, Materials.Grass, Materials.Sand, Materials.MossyStone,
            Materials.Water, Materials.Snow, Materials.Sandstone, Materials.JungleGrass,
            Materials.Deepstone,
        };
        var missing = MaterialPalette.Missing;
        foreach (byte id in generated)
        {
            var c = MaterialPalette.Of(id);
            Assert.IsFalse(c.R == missing.R && c.G == missing.G && c.B == missing.B,
                $"material {id} is generated by world-gen but has no authored colour");
        }
    }

    [Test]
    public void LavaIsTheOnlySelfLitMaterial()
    {
        // The self-lit path skips AO and the hemisphere term. Anything else
        // acquiring that flag would silently stop receiving shading.
        for (int i = 0; i < 256; i++)
            Assert.AreEqual(i == Materials.Lava, MaterialPalette.IsSelfLit((byte)i),
                $"material {i} self-lit flag unexpected");
    }
}
